In [1]:
import pandas as pd
import numpy as np

print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------


In [6]:
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("Series:")
print(s1_1)
print("\nNumPy Array:")
print(np_array1_2)
print("\nDataFrame:")
print(df1_3)


--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array:
[[ 8 47 65 54]
 [76 21 69 68]
 [59 88 90 18]]

DataFrame:
    A   B   C   D
0   8  47  65  54
1  76  21  69  68
2  59  88  90  18


In [7]:
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=100)
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})
sales_nan_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[sales_nan_indices, 'Sales'] = np.nan
quantity_nan_indices = np.random.choice(df_sales.index, size=3, replace=False)
df_sales.loc[quantity_nan_indices, 'Quantity'] = np.nan
print(df_sales)



--- Task 2: Synthetic Data Generation for Practice ---
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000  North     Mouse  549.0       7.0
1  2023-01-01 23:45:27.272727272  South   Monitor  968.0       8.0
2  2023-01-02 23:30:54.545454545   East    Laptop  327.0       9.0
3  2023-01-03 23:16:21.818181818   East    Laptop  463.0       3.0
4  2023-01-04 23:01:49.090909090   East   Monitor  832.0       7.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910  North  Keyboard  340.0       1.0
96 2023-04-06 00:43:38.181818182   West   Monitor  415.0       3.0
97 2023-04-07 00:29:05.454545455   West   Monitor  285.0       4.0
98 2023-04-08 00:14:32.727272728  North   Monitor  858.0       NaN
99 2023-04-09 00:00:00.000000000   West    Laptop  308.0       2.0

[100 rows x 5 columns]


In [9]:
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
df3_1 = df_sales[['Region', 'Sales']]
df3_2 = df_sales.loc[df_sales['Product'] == 'Laptop']
df3_3 = df_sales.loc[
    (df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)
]
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]



--- Task 3: Indexing and Slicing in DataFrames ---


In [10]:
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
missing_counts4_1 = df_sales.isna().sum()
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(
    df4_2_filled['Sales'].mean()
)
df4_3_dropped = df_sales.dropna()



--- Task 4: Data Cleaning (Handling Missing Values) ---


In [11]:
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()



--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---
